import type { Course } from '@/types';

const provider = (id: string, name: string): Course['instructor'] => ({ id, name, title: 'External learning provider', avatarUrl: '', rating: 0, students: 0 });

// The student catalogue remains empty until the instructor portal publishes
// real Akademia courses. External-provider courses are intentionally not shown.
export const externalCourses: Course[] = [
  { id: 'ext-ml', slug: 'machine-learning-specialization', title: 'Machine Learning Specialization', subtitle: 'Learn modern machine learning foundations.', description: 'A DeepLearning.AI programme on supervised learning, neural networks, and decision trees.', category: 'AI & ML', difficulty: 'Beginner' as const, thumbnailUrl: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&w=1200&q=80', rating: 4.9, reviews: 0, enrolled: 0, durationHours: 0, instructor: provider('deeplearning-ai', 'DeepLearning.AI'), tags: ['Machine Learning', 'Python', 'Neural Networks'], modules: [], status: 'not-started' as const, progress: 0, provider: 'DeepLearning.AI', externalUrl: 'https://www.deeplearning.ai/specializations/machine-learning' },
  { id: 'ext-kaggle', slug: 'kaggle-intro-machine-learning', title: 'Intro to Machine Learning', subtitle: 'Build your first machine-learning models.', description: 'A hands-on Kaggle course covering model training, validation, and prediction.', category: 'AI & ML', difficulty: 'Beginner' as const, thumbnailUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80', rating: 4.8, reviews: 0, enrolled: 0, durationHours: 0, instructor: provider('kaggle', 'Kaggle'), tags: ['Machine Learning', 'Model Validation', 'Python'], modules: [], status: 'not-started' as const, progress: 0, provider: 'Kaggle Learn', externalUrl: 'https://www.kaggle.com/learn/intro-to-machine-learning' },
  { id: 'ext-data', slug: 'google-data-analytics', title: 'Google Data Analytics Professional Certificate', subtitle: 'Develop job-ready data analytics skills.', description: 'Learn data cleaning, analysis, visualisation, and common analyst tools.', category: 'Data Science', difficulty: 'Beginner' as const, thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80', rating: 4.8, reviews: 0, enrolled: 0, durationHours: 0, instructor: provider('google', 'Google'), tags: ['Data Analytics', 'Spreadsheets', 'SQL'], modules: [], status: 'not-started' as const, progress: 0, provider: 'Coursera', externalUrl: 'https://www.coursera.org/professional-certificates/google-data-analytics' },
  { id: 'ext-web', slug: 'responsive-web-design', title: 'Responsive Web Design', subtitle: 'Learn HTML and CSS by building projects.', description: 'A project-based responsive web design certification from freeCodeCamp.', category: 'Web Development', difficulty: 'Beginner' as const, thumbnailUrl: 'https://images.unsplash.com/photo-1547658719-da2b51169166?auto=format&fit=crop&w=1200&q=80', rating: 4.8, reviews: 0, enrolled: 0, durationHours: 0, instructor: provider('freecodecamp', 'freeCodeCamp'), tags: ['HTML', 'CSS', 'Responsive Design'], modules: [], status: 'not-started' as const, progress: 0, provider: 'freeCodeCamp', externalUrl: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/' },
].slice(0, 0);
