import type { Quiz, Lab, Skill, Achievement } from '@/types';

export const quizzes: Quiz[] = [
  {
    id: 'q_1',
    title: 'Attention Mechanics',
    description: 'Test your understanding of self-attention, multi-head attention, and positional encoding.',
    category: 'AI & ML',
    difficulty: 'Advanced',
    questionCount: 5,
    estimatedMinutes: 10,
    bestScore: 95,
    attempts: 3,
    lastAttempted: '2025-08-01',
    questions: [
      {
        id: 'q1_1',
        question: 'In scaled dot-product attention, why do we divide QKᵀ by √d_k?',
        options: [
          'To speed up computation',
          'To keep gradient variance stable as dimensionality grows',
          'To normalize the embeddings to unit length',
          'To prevent attention weights from becoming negative',
        ],
        correctIndex: 1,
        explanation:
          'As d_k grows, dot products get large, pushing softmax into regions with tiny gradients. Dividing by √d_k keeps variance stable.',
      },
      {
        id: 'q1_2',
        question: 'What does the Value (V) matrix represent in attention?',
        options: [
          'What am I looking for?',
          'What do I contain?',
          'What information do I pass along?',
          'How important is this token?',
        ],
        correctIndex: 2,
        explanation:
          'Query = "what am I looking for", Key = "what do I contain", Value = "what information do I pass along".',
      },
      {
        id: 'q1_3',
        question: 'Multi-head attention runs h parallel heads primarily to:',
        options: [
          'Reduce total computation',
          'Allow the model to attend to different relationships simultaneously',
          'Increase the receptive field',
          'Replace the need for positional encoding',
        ],
        correctIndex: 1,
        explanation:
          'Different heads can learn to track different relationships — one might focus on syntax, another on semantics.',
      },
      {
        id: 'q1_4',
        question: 'Positional encodings are needed in transformers because:',
        options: [
          'Self-attention is permutation-invariant',
          'They replace the need for embeddings',
          'They reduce overfitting',
          'They normalize activations',
        ],
        correctIndex: 0,
        explanation:
          'Without positional encoding, attention treats the input as a bag of tokens — order does not matter. Positional encodings inject order information.',
      },
      {
        id: 'q1_5',
        question: 'In multi-head attention, each head projects Q, K, V into a space of dimension:',
        options: [
          'd_model',
          'd_model / h',
          'h × d_model',
          'd_k only',
        ],
        correctIndex: 1,
        explanation:
          'Each head operates in a lower-dimensional space d_model/h so the total computational cost stays the same as single-head attention.',
      },
    ],
  },
  {
    id: 'q_2',
    title: 'RAG Fundamentals',
    description: 'Cover retrieval-augmented generation architecture, chunking, and eval basics.',
    category: 'AI & ML',
    difficulty: 'Intermediate',
    questionCount: 5,
    estimatedMinutes: 8,
    bestScore: 80,
    attempts: 2,
    lastAttempted: '2025-07-28',
    questions: [
      {
        id: 'q2_1',
        question: 'What is the primary purpose of RAG?',
        options: [
          'Fine-tune a model on domain data',
          'Give an LLM access to external knowledge at inference time',
          'Reduce model latency',
          'Compress model parameters',
        ],
        correctIndex: 1,
        explanation:
          'RAG retrieves relevant documents and feeds them as context to the LLM, grounding responses in external knowledge without fine-tuning.',
      },
      {
        id: 'q2_2',
        question: 'A good starting chunk size for most RAG systems is approximately:',
        options: ['64 tokens', '512 tokens', '4096 tokens', '8192 tokens'],
        correctIndex: 1,
        explanation:
          '512 tokens is a common starting point. You should tune this based on your eval set — measure recall@k for different sizes.',
      },
      {
        id: 'q2_3',
        question: 'Why add overlap between chunks?',
        options: [
          'To increase total storage',
          'To prevent splitting ideas across chunk boundaries',
          'To speed up retrieval',
          'To reduce embedding dimension',
        ],
        correctIndex: 1,
        explanation:
          'Overlap (10-20%) ensures that ideas spanning a chunk boundary are not lost — both chunks will contain the boundary text.',
      },
      {
        id: 'q2_4',
        question: 'Hybrid search combines which two methods?',
        options: [
          'BM25 keyword search and vector search',
          'SQL and NoSQL queries',
          'CNN and LSTM',
          'PCA and t-SNE',
        ],
        correctIndex: 0,
        explanation:
          'Hybrid search combines BM25 (keyword/lexical) with vector (semantic) search for better recall, especially on queries with rare terms.',
      },
      {
        id: 'q2_5',
        question: 'What does "eval-first development" mean for LLM apps?',
        options: [
          'Build evals before building features',
          'Evaluate only after deployment',
          'Use only automated metrics',
          'Skip evals for prototypes',
        ],
        correctIndex: 0,
        explanation:
          'Build your evaluation set and metrics first, then build features. This ensures you can measure whether changes actually improve the system.',
      },
    ],
  },
  {
    id: 'q_3',
    title: 'Python Data Structures',
    description: 'Lists, dicts, sets, and comprehensions — the building blocks.',
    category: 'Web Development',
    difficulty: 'Beginner',
    questionCount: 5,
    estimatedMinutes: 6,
    bestScore: 100,
    attempts: 1,
    lastAttempted: '2025-07-15',
    questions: [
      {
        id: 'q3_1',
        question: 'What is the time complexity of looking up a key in a Python dict (average case)?',
        options: ['O(n)', 'O(log n)', 'O(1)', 'O(n log n)'],
        correctIndex: 2,
        explanation: 'Python dicts use hash tables, giving O(1) average-case lookup, insertion, and deletion.',
      },
      {
        id: 'q3_2',
        question: 'Which comprehension creates a set of squares from 0 to 4?',
        options: [
          '[x**2 for x in range(5)]',
          '{x**2 for x in range(5)}',
          '(x**2 for x in range(5))',
          'dict(x**2 for x in range(5))',
        ],
        correctIndex: 1,
        explanation: 'Curly braces with a comprehension create a set. Square brackets create a list, parentheses create a generator.',
      },
      {
        id: 'q3_3',
        question: 'What does list.append() do vs list.extend()?',
        options: [
          'They are identical',
          'append adds one element; extend adds all elements from an iterable',
          'append adds to the front; extend adds to the back',
          'append is faster than extend',
        ],
        correctIndex: 1,
        explanation: 'append(x) adds a single element x. extend(iterable) adds each element from the iterable individually.',
      },
      {
        id: 'q3_4',
        question: 'Which is NOT a valid way to remove duplicates from a list?',
        options: [
          'list(set(items))',
          'list(dict.fromkeys(items))',
          'items.remove_duplicates()',
          'Using a loop with a seen set',
        ],
        correctIndex: 2,
        explanation: 'Python lists have no remove_duplicates method. The other three approaches all work, though set() does not preserve order.',
      },
      {
        id: 'q3_5',
        question: 'What is a defaultdict?',
        options: [
          'A dict with default permissions',
          'A dict subclass that provides a default value for missing keys',
          'A dict that cannot be modified',
          'A dict that auto-sorts by key',
        ],
        correctIndex: 1,
        explanation: 'defaultdict takes a factory function. When a missing key is accessed, it calls the factory to create a default value instead of raising KeyError.',
      },
    ],
  },
  {
    id: 'q_4',
    title: 'Statistical Inference',
    description: 'Hypothesis testing, p-values, confidence intervals, and common pitfalls.',
    category: 'Data Science',
    difficulty: 'Intermediate',
    questionCount: 5,
    estimatedMinutes: 10,
    bestScore: 0,
    attempts: 0,
    lastAttempted: null,
    questions: [
      {
        id: 'q4_1',
        question: 'A p-value of 0.04 means:',
        options: [
          'There is a 4% probability the null hypothesis is true',
          'There is a 4% probability of seeing results at least this extreme if the null hypothesis is true',
          'The effect size is 4%',
          'The study has 96% power',
        ],
        correctIndex: 1,
        explanation:
          'The p-value is the probability of observing results at least as extreme as the data, assuming the null hypothesis is true. It is NOT the probability that the null is true.',
      },
      {
        id: 'q4_2',
        question: 'A 95% confidence interval means:',
        options: [
          '95% of the data falls within the interval',
          'If we repeated the experiment many times, 95% of the intervals would contain the true parameter',
          'There is a 95% probability the true parameter is in this specific interval',
          'The margin of error is 5%',
        ],
        correctIndex: 1,
        explanation:
          'The confidence level refers to the procedure: 95% of intervals constructed this way would capture the true parameter. A specific interval either contains it or does not.',
      },
      {
        id: 'q4_3',
        question: 'What is the main risk of multiple comparisons without correction?',
        options: [
          'Increased Type II error',
          'Increased Type I error (false positives)',
          'Biased estimates',
          'Overfitting',
        ],
        correctIndex: 1,
        explanation:
          'With many tests, the chance of at least one false positive increases. Bonferroni or FDR corrections control this family-wise error rate.',
      },
      {
        id: 'q4_4',
        question: 'Statistical power is the probability of:',
        options: [
          'Correctly rejecting a false null hypothesis',
          'Correctly failing to reject a true null hypothesis',
          'Getting a significant p-value',
          'Replicating the result',
        ],
        correctIndex: 0,
        explanation: 'Power = 1 - β. It is the probability of detecting a true effect (correctly rejecting a false null). Higher power means fewer Type II errors.',
      },
      {
        id: 'q4_5',
        question: 'Which is NOT an assumption of a standard t-test?',
        options: [
          'Normality of the data or residuals',
          'Independence of observations',
          'Equal variances (for two-sample)',
          'The sample size must be at least 1000',
        ],
        correctIndex: 3,
        explanation:
          'There is no hard requirement for n ≥ 1000. With small samples the normality assumption matters more; with large samples the CLT helps.',
      },
    ],
  },
  {
    id: 'q_5',
    title: 'React Hooks Deep Dive',
    description: 'useState, useEffect, useMemo, useCallback, and custom hooks.',
    category: 'Web Development',
    difficulty: 'Intermediate',
    questionCount: 5,
    estimatedMinutes: 8,
    bestScore: 0,
    attempts: 0,
    lastAttempted: null,
    questions: [
      {
        id: 'q5_1',
        question: 'What does the dependency array [ ] (empty) in useEffect do?',
        options: [
          'Runs the effect on every render',
          'Runs the effect only once on mount',
          'Never runs the effect',
          'Runs the effect only on unmount',
        ],
        correctIndex: 1,
        explanation:
          'An empty dependency array means the effect has no dependencies, so it runs once after the initial render (and cleanup runs on unmount).',
      },
      {
        id: 'q5_2',
        question: 'When should you use useMemo?',
        options: [
          'To memoize any function',
          'To cache an expensive computed value between renders unless dependencies change',
          'To prevent re-renders entirely',
          'To replace useState',
        ],
        correctIndex: 1,
        explanation:
          'useMemo caches a computed value and only recomputes when dependencies change. Use it for expensive calculations, not for trivial ones.',
      },
      {
        id: 'q5_3',
        question: 'What is a closure "stale value" bug in React?',
        options: [
          'A bug where useEffect captures an old state value because dependencies were omitted',
          'A memory leak from too many closures',
          'A TypeScript compilation error',
          'A React DevTools display issue',
        ],
        correctIndex: 0,
        explanation:
          'If you omit a variable from the dependency array, the effect closure captures the value from the render when it was created, leading to stale state.',
      },
      {
        id: 'q5_4',
        question: 'useCallback is primarily used to:',
        options: [
          'Memoize a function reference so it stays stable across renders',
          'Call an API',
          'Schedule a delayed callback',
          'Replace event listeners',
        ],
        correctIndex: 0,
        explanation:
          'useCallback returns a memoized function. This is useful when passing callbacks to memoized child components to prevent unnecessary re-renders.',
      },
      {
        id: 'q5_5',
        question: 'Custom hooks must:',
        options: [
          'Start with the prefix "use"',
          'Be defined in a separate file',
          'Only call other built-in hooks',
          'Return a value',
        ],
        correctIndex: 0,
        explanation:
          'The "use" prefix is a convention that React relies on (via lint rules) to identify hooks. Custom hooks can call other hooks and may return anything.',
      },
    ],
  },
  {
    id: 'q_6',
    title: 'SQL Window Functions',
    description: 'RANK, ROW_NUMBER, partitions, and running totals.',
    category: 'Data Science',
    difficulty: 'Advanced',
    questionCount: 5,
    estimatedMinutes: 8,
    bestScore: 0,
    attempts: 0,
    lastAttempted: null,
    questions: [
      {
        id: 'q6_1',
        question: 'What is the difference between RANK() and ROW_NUMBER()?',
        options: [
          'They are identical',
          'RANK gives ties the same rank; ROW_NUMBER always gives a unique number',
          'ROW_NUMBER skips ties',
          'RANK only works with ascending order',
        ],
        correctIndex: 1,
        explanation:
          'RANK() assigns the same rank to ties and skips the next ranks (1,1,3). ROW_NUMBER() always assigns sequential unique numbers (1,2,3).',
      },
      {
        id: 'q6_2',
        question: 'What does PARTITION BY do in a window function?',
        options: [
          'Divides the table into separate physical files',
          'Resets the window calculation for each group',
          'Filters rows before the window function runs',
          'Sorts the output',
        ],
        correctIndex: 1,
        explanation:
          'PARTITION BY groups rows, and the window function resets its computation within each group — like a GROUP BY that keeps all rows.',
      },
      {
        id: 'q6_3',
        question: 'Which window function computes a running total?',
        options: ['LAG()', 'LEAD()', 'SUM() OVER (ORDER BY ...)', 'NTILE()'],
        correctIndex: 2,
        explanation:
          'SUM(column) OVER (ORDER BY some_col) computes a cumulative sum. Without ORDER BY it gives the grand total for the partition.',
      },
      {
        id: 'q6_4',
        question: 'ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING defines a window of:',
        options: [
          'The current row only',
          '3 rows: the previous, current, and next row',
          'All rows before the current row',
          'The first and last row',
        ],
        correctIndex: 1,
        explanation:
          'This frame includes one row before, the current row, and one row after — a 3-row sliding window.',
      },
      {
        id: 'q6_5',
        question: 'Unlike GROUP BY, window functions:',
        options: [
          'Collapse rows into one per group',
          'Keep all rows and add a computed column across the group',
          'Cannot use aggregation',
          'Are faster',
        ],
        correctIndex: 1,
        explanation:
          'GROUP BY collapses each group into a single row. Window functions keep all rows and append a value computed across the partition.',
      },
    ],
  },
];

export const labs: Lab[] = [
  {
    id: 'lab_1',
    title: 'Implement Multi-Head Attention',
    description: 'Build multi-head attention from scratch in PyTorch. Pass shape checks and gradient tests.',
    category: 'AI & ML',
    difficulty: 'Advanced',
    estimatedMinutes: 45,
    techStack: ['PyTorch', 'Python', 'NumPy'],
    thumbnailUrl:
      'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&h=250&fit=crop&q=80',
    status: 'in-progress',
    progress: 60,
    skills: ['Attention', 'PyTorch', 'Tensor Operations'],
  },
  {
    id: 'lab_2',
    title: 'Build a RAG Pipeline',
    description: 'Create a retrieval-augmented generation pipeline with embeddings, a vector store, and evals.',
    category: 'AI & ML',
    difficulty: 'Intermediate',
    estimatedMinutes: 60,
    techStack: ['LangChain', 'Python', 'Pinecone'],
    thumbnailUrl:
      'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=250&fit=crop&q=80',
    status: 'not-started',
    progress: 0,
    skills: ['RAG', 'Embeddings', 'Vector Search'],
  },
  {
    id: 'lab_3',
    title: 'SQL Window Functions Workshop',
    description: 'Solve 10 real-world analytics problems using RANK, LAG, and running totals.',
    category: 'Data Science',
    difficulty: 'Intermediate',
    estimatedMinutes: 30,
    techStack: ['PostgreSQL', 'SQL'],
    thumbnailUrl:
      'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400&h=250&fit=crop&q=80',
    status: 'completed',
    progress: 100,
    skills: ['SQL', 'Window Functions', 'Analytics'],
  },
  {
    id: 'lab_4',
    title: 'Train a CNN Image Classifier',
    description: 'Build, train, and evaluate a convolutional network on CIFAR-10 with data augmentation.',
    category: 'AI & ML',
    difficulty: 'Advanced',
    estimatedMinutes: 90,
    techStack: ['PyTorch', 'Python', 'Matplotlib'],
    thumbnailUrl:
      'https://images.unsplash.com/photo-1563089145-599497fcc34f?w=400&h=250&fit=crop&q=80',
    status: 'not-started',
    progress: 0,
    skills: ['CNN', 'Image Classification', 'Data Augmentation'],
  },
  {
    id: 'lab_5',
    title: 'Build a React Custom Hook',
    description: 'Create a useDebounce hook and a useLocalStorage hook with full TypeScript types.',
    category: 'Web Development',
    difficulty: 'Beginner',
    estimatedMinutes: 25,
    techStack: ['React', 'TypeScript'],
    thumbnailUrl:
      'https://images.unsplash.com/photo-1633356122544-f073ef97b911?w=400&h=250&fit=crop&q=80',
    status: 'not-started',
    progress: 0,
    skills: ['React Hooks', 'TypeScript', 'Debounce'],
  },
  {
    id: 'lab_6',
    title: 'Positional Encoding Implementation',
    description: 'Implement sinusoidal and learned positional encodings, then compare on a copy task.',
    category: 'AI & ML',
    difficulty: 'Intermediate',
    estimatedMinutes: 35,
    techStack: ['PyTorch', 'Python'],
    thumbnailUrl:
      'https://images.unsplash.com/photo-1518186285589-98f764515d60?w=400&h=250&fit=crop&q=80',
    status: 'completed',
    progress: 100,
    skills: ['Positional Encoding', 'Transformers'],
  },
  {
    id: 'lab_7',
    title: 'Gradient Descent from Scratch',
    description: 'Implement vanilla, momentum, and Adam optimizers without any library. Visualize the descent.',
    category: 'AI & ML',
    difficulty: 'Beginner',
    estimatedMinutes: 40,
    techStack: ['Python', 'NumPy', 'Matplotlib'],
    thumbnailUrl:
      'https://images.unsplash.com/photo-1555949963-ff9fe0c895e4?w=400&h=250&fit=crop&q=80',
    status: 'not-started',
    progress: 0,
    skills: ['Optimization', 'Gradient Descent', 'Adam'],
  },
  {
    id: 'lab_8',
    title: 'Deploy an ML Model with FastAPI',
    description: 'Wrap a trained model in a FastAPI service, add health checks, and deploy to a container.',
    category: 'AI & ML',
    difficulty: 'Advanced',
    estimatedMinutes: 50,
    techStack: ['FastAPI', 'Docker', 'Python'],
    thumbnailUrl:
      'https://images.unsplash.com/photo-1451187580459-9546291f6b25?w=400&h=250&fit=crop&q=80',
    status: 'not-started',
    progress: 0,
    skills: ['MLOps', 'FastAPI', 'Docker'],
  },
];

export const extendedSkills: Skill[] = [
  { id: 's_1', name: 'PyTorch', proficiency: 78, category: 'Frameworks' },
  { id: 's_2', name: 'Python', proficiency: 92, category: 'Languages' },
  { id: 's_3', name: 'Statistics', proficiency: 85, category: 'Math' },
  { id: 's_4', name: 'RAG Systems', proficiency: 54, category: 'AI & ML' },
  { id: 's_5', name: 'TypeScript', proficiency: 71, category: 'Languages' },
  { id: 's_6', name: 'Vector Databases', proficiency: 40, category: 'Infrastructure' },
  { id: 's_7', name: 'SQL', proficiency: 88, category: 'Languages' },
  { id: 's_8', name: 'React', proficiency: 67, category: 'Frameworks' },
  { id: 's_9', name: 'Linear Algebra', proficiency: 80, category: 'Math' },
  { id: 's_10', name: 'Docker', proficiency: 45, category: 'Infrastructure' },
  { id: 's_11', name: 'Prompt Engineering', proficiency: 75, category: 'AI & ML' },
  { id: 's_12', name: 'Attention Mechanisms', proficiency: 82, category: 'AI & ML' },
];

export const extendedAchievements: Achievement[] = [
  {
    id: 'a_1',
    title: 'Weekend Warrior',
    description: 'Study 4 weekends in a row',
    icon: 'Flame',
    unlockedAt: '2025-07-28',
    rarity: 'rare',
  },
  {
    id: 'a_2',
    title: 'Quiz Master',
    description: 'Pass 50 quizzes with 90%+ score',
    icon: 'Brain',
    unlockedAt: '2025-07-20',
    rarity: 'epic',
  },
  {
    id: 'a_3',
    title: 'First Steps',
    description: 'Complete your first course',
    icon: 'Footprints',
    unlockedAt: '2025-06-15',
    rarity: 'common',
  },
  {
    id: 'a_4',
    title: 'Streak Keeper',
    description: 'Maintain a 20-day streak',
    icon: 'Zap',
    unlockedAt: '2025-08-01',
    rarity: 'legendary',
  },
  {
    id: 'a_5',
    title: 'Lab Rat',
    description: 'Complete 10 hands-on labs',
    icon: 'FlaskConical',
    unlockedAt: null,
    rarity: 'rare',
  },
  {
    id: 'a_6',
    title: 'Polyglot',
    description: 'Learn 3 programming languages',
    icon: 'Languages',
    unlockedAt: null,
    rarity: 'epic',
  },
  {
    id: 'a_7',
    title: 'Night Owl',
    description: 'Study after midnight 10 times',
    icon: 'Moon',
    unlockedAt: null,
    rarity: 'common',
  },
  {
    id: 'a_8',
    title: 'Graduation Day',
    description: 'Complete an entire learning path',
    icon: 'GraduationCap',
    unlockedAt: null,
    rarity: 'legendary',
  },
  {
    id: 'a_9',
    title: 'Helping Hand',
    description: 'Answer 25 community questions',
    icon: 'HeartHandshake',
    unlockedAt: null,
    rarity: 'common',
  },
  {
    id: 'a_10',
    title: 'Speed Runner',
    description: 'Finish a course in under 7 days',
    icon: 'Rocket',
    unlockedAt: '2025-07-05',
    rarity: 'rare',
  },
  {
    id: 'a_11',
    title: 'AI Whisperer',
    description: 'Have 100 AI coaching conversations',
    icon: 'Sparkles',
    unlockedAt: null,
    rarity: 'epic',
  },
  {
    id: 'a_12',
    title: 'Perfectionist',
    description: 'Score 100% on 10 quizzes',
    icon: 'Target',
    unlockedAt: '2025-07-15',
    rarity: 'epic',
  },
];
